/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as PastebinKeyRouteImport } from './routes/pastebin-key'
import { Route as CodeRouteImport } from './routes/code'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTags_writeRouteImport } from './routes/api/public/tags_write'
import { Route as ApiPublicTagsRouteImport } from './routes/api/public/tags'
import { Route as ApiPublicTag_groupsRouteImport } from './routes/api/public/tag_groups'
import { Route as ApiPublicRolesRouteImport } from './routes/api/public/roles'
import { Route as ApiPublicReanimDotluaRouteImport } from './routes/api/public/reanim[.]lua'
import { Route as ApiPublicPastebinRouteImport } from './routes/api/public/pastebin'
import { Route as ApiPublicAdminDotluaRouteImport } from './routes/api/public/admin[.]lua'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const PastebinKeyRoute = PastebinKeyRouteImport.update({
  id: '/pastebin-key',
  path: '/pastebin-key',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTags_writeRoute = ApiPublicTags_writeRouteImport.update({
  id: '/api/public/tags_write',
  path: '/api/public/tags_write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTagsRoute = ApiPublicTagsRouteImport.update({
  id: '/api/public/tags',
  path: '/api/public/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTag_groupsRoute = ApiPublicTag_groupsRouteImport.update({
  id: '/api/public/tag_groups',
  path: '/api/public/tag_groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRolesRoute = ApiPublicRolesRouteImport.update({
  id: '/api/public/roles',
  path: '/api/public/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReanimDotluaRoute = ApiPublicReanimDotluaRouteImport.update({
  id: '/api/public/reanim.lua',
  path: '/api/public/reanim.lua',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPastebinRoute = ApiPublicPastebinRouteImport.update({
  id: '/api/public/pastebin',
  path: '/api/public/pastebin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDotluaRoute = ApiPublicAdminDotluaRouteImport.update({
  id: '/api/public/admin.lua',
  path: '/api/public/admin.lua',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/unlock': typeof UnlockRoute
  '/api/public/admin.lua': typeof ApiPublicAdminDotluaRoute
  '/api/public/pastebin': typeof ApiPublicPastebinRoute
  '/api/public/reanim.lua': typeof ApiPublicReanimDotluaRoute
  '/api/public/roles': typeof ApiPublicRolesRoute
  '/api/public/tag_groups': typeof ApiPublicTag_groupsRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/api/public/tags_write': typeof ApiPublicTags_writeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/unlock': typeof UnlockRoute
  '/api/public/admin.lua': typeof ApiPublicAdminDotluaRoute
  '/api/public/pastebin': typeof ApiPublicPastebinRoute
  '/api/public/reanim.lua': typeof ApiPublicReanimDotluaRoute
  '/api/public/roles': typeof ApiPublicRolesRoute
  '/api/public/tag_groups': typeof ApiPublicTag_groupsRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/api/public/tags_write': typeof ApiPublicTags_writeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/unlock': typeof UnlockRoute
  '/api/public/admin.lua': typeof ApiPublicAdminDotluaRoute
  '/api/public/pastebin': typeof ApiPublicPastebinRoute
  '/api/public/reanim.lua': typeof ApiPublicReanimDotluaRoute
  '/api/public/roles': typeof ApiPublicRolesRoute
  '/api/public/tag_groups': typeof ApiPublicTag_groupsRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/api/public/tags_write': typeof ApiPublicTags_writeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code'
    | '/pastebin-key'
    | '/unlock'
    | '/api/public/admin.lua'
    | '/api/public/pastebin'
    | '/api/public/reanim.lua'
    | '/api/public/roles'
    | '/api/public/tag_groups'
    | '/api/public/tags'
    | '/api/public/tags_write'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code'
    | '/pastebin-key'
    | '/unlock'
    | '/api/public/admin.lua'
    | '/api/public/pastebin'
    | '/api/public/reanim.lua'
    | '/api/public/roles'
    | '/api/public/tag_groups'
    | '/api/public/tags'
    | '/api/public/tags_write'
  id:
    | '__root__'
    | '/'
    | '/code'
    | '/pastebin-key'
    | '/unlock'
    | '/api/public/admin.lua'
    | '/api/public/pastebin'
    | '/api/public/reanim.lua'
    | '/api/public/roles'
    | '/api/public/tag_groups'
    | '/api/public/tags'
    | '/api/public/tags_write'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  PastebinKeyRoute: typeof PastebinKeyRoute
  UnlockRoute: typeof UnlockRoute
  ApiPublicAdminDotluaRoute: typeof ApiPublicAdminDotluaRoute
  ApiPublicPastebinRoute: typeof ApiPublicPastebinRoute
  ApiPublicReanimDotluaRoute: typeof ApiPublicReanimDotluaRoute
  ApiPublicRolesRoute: typeof ApiPublicRolesRoute
  ApiPublicTag_groupsRoute: typeof ApiPublicTag_groupsRoute
  ApiPublicTagsRoute: typeof ApiPublicTagsRoute
  ApiPublicTags_writeRoute: typeof ApiPublicTags_writeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastebin-key': {
      id: '/pastebin-key'
      path: '/pastebin-key'
      fullPath: '/pastebin-key'
      preLoaderRoute: typeof PastebinKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tags_write': {
      id: '/api/public/tags_write'
      path: '/api/public/tags_write'
      fullPath: '/api/public/tags_write'
      preLoaderRoute: typeof ApiPublicTags_writeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tags': {
      id: '/api/public/tags'
      path: '/api/public/tags'
      fullPath: '/api/public/tags'
      preLoaderRoute: typeof ApiPublicTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tag_groups': {
      id: '/api/public/tag_groups'
      path: '/api/public/tag_groups'
      fullPath: '/api/public/tag_groups'
      preLoaderRoute: typeof ApiPublicTag_groupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roles': {
      id: '/api/public/roles'
      path: '/api/public/roles'
      fullPath: '/api/public/roles'
      preLoaderRoute: typeof ApiPublicRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reanim.lua': {
      id: '/api/public/reanim.lua'
      path: '/api/public/reanim.lua'
      fullPath: '/api/public/reanim.lua'
      preLoaderRoute: typeof ApiPublicReanimDotluaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pastebin': {
      id: '/api/public/pastebin'
      path: '/api/public/pastebin'
      fullPath: '/api/public/pastebin'
      preLoaderRoute: typeof ApiPublicPastebinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin.lua': {
      id: '/api/public/admin.lua'
      path: '/api/public/admin.lua'
      fullPath: '/api/public/admin.lua'
      preLoaderRoute: typeof ApiPublicAdminDotluaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  PastebinKeyRoute: PastebinKeyRoute,
  UnlockRoute: UnlockRoute,
  ApiPublicAdminDotluaRoute: ApiPublicAdminDotluaRoute,
  ApiPublicPastebinRoute: ApiPublicPastebinRoute,
  ApiPublicReanimDotluaRoute: ApiPublicReanimDotluaRoute,
  ApiPublicRolesRoute: ApiPublicRolesRoute,
  ApiPublicTag_groupsRoute: ApiPublicTag_groupsRoute,
  ApiPublicTagsRoute: ApiPublicTagsRoute,
  ApiPublicTags_writeRoute: ApiPublicTags_writeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
