/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PastebinKeyRouteImport } from './routes/pastebin-key'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPastebinRouteImport } from './routes/api/pastebin'

const PastebinKeyRoute = PastebinKeyRouteImport.update({
  id: '/pastebin-key',
  path: '/pastebin-key',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPastebinRoute = ApiPastebinRouteImport.update({
  id: '/api/pastebin',
  path: '/api/pastebin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/api/pastebin': typeof ApiPastebinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/api/pastebin': typeof ApiPastebinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/api/pastebin': typeof ApiPastebinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pastebin-key' | '/api/pastebin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pastebin-key' | '/api/pastebin'
  id: '__root__' | '/' | '/pastebin-key' | '/api/pastebin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PastebinKeyRoute: typeof PastebinKeyRoute
  ApiPastebinRoute: typeof ApiPastebinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pastebin-key': {
      id: '/pastebin-key'
      path: '/pastebin-key'
      fullPath: '/pastebin-key'
      preLoaderRoute: typeof PastebinKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pastebin': {
      id: '/api/pastebin'
      path: '/api/pastebin'
      fullPath: '/api/pastebin'
      preLoaderRoute: typeof ApiPastebinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PastebinKeyRoute: PastebinKeyRoute,
  ApiPastebinRoute: ApiPastebinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
