/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidateRouteImport } from './routes/validate'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as PastebinKeyRouteImport } from './routes/pastebin-key'
import { Route as GetKeyRouteImport } from './routes/get-key'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTags_writeRouteImport } from './routes/api/public/tags_write'
import { Route as ApiPublicTagsRouteImport } from './routes/api/public/tags'
import { Route as ApiPublicTag_sync_keyRouteImport } from './routes/api/public/tag_sync_key'
import { Route as ApiPublicTag_groupsRouteImport } from './routes/api/public/tag_groups'
import { Route as ApiPublicSpotify_callbackRouteImport } from './routes/api/public/spotify_callback'
import { Route as ApiPublicRolesRouteImport } from './routes/api/public/roles'
import { Route as ApiPublicReanimDotluaRouteImport } from './routes/api/public/reanim[.]lua'
import { Route as ApiPublicPastebinRouteImport } from './routes/api/public/pastebin'
import { Route as ApiPublicLoaderDotluaRouteImport } from './routes/api/public/loader[.]lua'
import { Route as ApiPublicAdminDotluaRouteImport } from './routes/api/public/admin[.]lua'
import { Route as ApiPublicKTokenRouteImport } from './routes/api/public/k.$token'

const ValidateRoute = ValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const PastebinKeyRoute = PastebinKeyRouteImport.update({
  id: '/pastebin-key',
  path: '/pastebin-key',
  getParentRoute: () => rootRouteImport,
} as any)
const GetKeyRoute = GetKeyRouteImport.update({
  id: '/get-key',
  path: '/get-key',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTags_writeRoute = ApiPublicTags_writeRouteImport.update({
  id: '/api/public/tags_write',
  path: '/api/public/tags_write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTagsRoute = ApiPublicTagsRouteImport.update({
  id: '/api/public/tags',
  path: '/api/public/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTag_sync_keyRoute = ApiPublicTag_sync_keyRouteImport.update({
  id: '/api/public/tag_sync_key',
  path: '/api/public/tag_sync_key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTag_groupsRoute = ApiPublicTag_groupsRouteImport.update({
  id: '/api/public/tag_groups',
  path: '/api/public/tag_groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSpotify_callbackRoute =
  ApiPublicSpotify_callbackRouteImport.update({
    id: '/api/public/spotify_callback',
    path: '/api/public/spotify_callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRolesRoute = ApiPublicRolesRouteImport.update({
  id: '/api/public/roles',
  path: '/api/public/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReanimDotluaRoute = ApiPublicReanimDotluaRouteImport.update({
  id: '/api/public/reanim.lua',
  path: '/api/public/reanim.lua',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPastebinRoute = ApiPublicPastebinRouteImport.update({
  id: '/api/public/pastebin',
  path: '/api/public/pastebin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLoaderDotluaRoute = ApiPublicLoaderDotluaRouteImport.update({
  id: '/api/public/loader.lua',
  path: '/api/public/loader.lua',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminDotluaRoute = ApiPublicAdminDotluaRouteImport.update({
  id: '/api/public/admin.lua',
  path: '/api/public/admin.lua',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKTokenRoute = ApiPublicKTokenRouteImport.update({
  id: '/api/public/k/$token',
  path: '/api/public/k/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-key': typeof GetKeyRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/unlock': typeof UnlockRoute
  '/validate': typeof ValidateRoute
  '/api/public/admin.lua': typeof ApiPublicAdminDotluaRoute
  '/api/public/loader.lua': typeof ApiPublicLoaderDotluaRoute
  '/api/public/pastebin': typeof ApiPublicPastebinRoute
  '/api/public/reanim.lua': typeof ApiPublicReanimDotluaRoute
  '/api/public/roles': typeof ApiPublicRolesRoute
  '/api/public/spotify_callback': typeof ApiPublicSpotify_callbackRoute
  '/api/public/tag_groups': typeof ApiPublicTag_groupsRoute
  '/api/public/tag_sync_key': typeof ApiPublicTag_sync_keyRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/api/public/tags_write': typeof ApiPublicTags_writeRoute
  '/api/public/k/$token': typeof ApiPublicKTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-key': typeof GetKeyRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/unlock': typeof UnlockRoute
  '/validate': typeof ValidateRoute
  '/api/public/admin.lua': typeof ApiPublicAdminDotluaRoute
  '/api/public/loader.lua': typeof ApiPublicLoaderDotluaRoute
  '/api/public/pastebin': typeof ApiPublicPastebinRoute
  '/api/public/reanim.lua': typeof ApiPublicReanimDotluaRoute
  '/api/public/roles': typeof ApiPublicRolesRoute
  '/api/public/spotify_callback': typeof ApiPublicSpotify_callbackRoute
  '/api/public/tag_groups': typeof ApiPublicTag_groupsRoute
  '/api/public/tag_sync_key': typeof ApiPublicTag_sync_keyRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/api/public/tags_write': typeof ApiPublicTags_writeRoute
  '/api/public/k/$token': typeof ApiPublicKTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-key': typeof GetKeyRoute
  '/pastebin-key': typeof PastebinKeyRoute
  '/unlock': typeof UnlockRoute
  '/validate': typeof ValidateRoute
  '/api/public/admin.lua': typeof ApiPublicAdminDotluaRoute
  '/api/public/loader.lua': typeof ApiPublicLoaderDotluaRoute
  '/api/public/pastebin': typeof ApiPublicPastebinRoute
  '/api/public/reanim.lua': typeof ApiPublicReanimDotluaRoute
  '/api/public/roles': typeof ApiPublicRolesRoute
  '/api/public/spotify_callback': typeof ApiPublicSpotify_callbackRoute
  '/api/public/tag_groups': typeof ApiPublicTag_groupsRoute
  '/api/public/tag_sync_key': typeof ApiPublicTag_sync_keyRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/api/public/tags_write': typeof ApiPublicTags_writeRoute
  '/api/public/k/$token': typeof ApiPublicKTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-key'
    | '/pastebin-key'
    | '/unlock'
    | '/validate'
    | '/api/public/admin.lua'
    | '/api/public/loader.lua'
    | '/api/public/pastebin'
    | '/api/public/reanim.lua'
    | '/api/public/roles'
    | '/api/public/spotify_callback'
    | '/api/public/tag_groups'
    | '/api/public/tag_sync_key'
    | '/api/public/tags'
    | '/api/public/tags_write'
    | '/api/public/k/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-key'
    | '/pastebin-key'
    | '/unlock'
    | '/validate'
    | '/api/public/admin.lua'
    | '/api/public/loader.lua'
    | '/api/public/pastebin'
    | '/api/public/reanim.lua'
    | '/api/public/roles'
    | '/api/public/spotify_callback'
    | '/api/public/tag_groups'
    | '/api/public/tag_sync_key'
    | '/api/public/tags'
    | '/api/public/tags_write'
    | '/api/public/k/$token'
  id:
    | '__root__'
    | '/'
    | '/get-key'
    | '/pastebin-key'
    | '/unlock'
    | '/validate'
    | '/api/public/admin.lua'
    | '/api/public/loader.lua'
    | '/api/public/pastebin'
    | '/api/public/reanim.lua'
    | '/api/public/roles'
    | '/api/public/spotify_callback'
    | '/api/public/tag_groups'
    | '/api/public/tag_sync_key'
    | '/api/public/tags'
    | '/api/public/tags_write'
    | '/api/public/k/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetKeyRoute: typeof GetKeyRoute
  PastebinKeyRoute: typeof PastebinKeyRoute
  UnlockRoute: typeof UnlockRoute
  ValidateRoute: typeof ValidateRoute
  ApiPublicAdminDotluaRoute: typeof ApiPublicAdminDotluaRoute
  ApiPublicLoaderDotluaRoute: typeof ApiPublicLoaderDotluaRoute
  ApiPublicPastebinRoute: typeof ApiPublicPastebinRoute
  ApiPublicReanimDotluaRoute: typeof ApiPublicReanimDotluaRoute
  ApiPublicRolesRoute: typeof ApiPublicRolesRoute
  ApiPublicSpotify_callbackRoute: typeof ApiPublicSpotify_callbackRoute
  ApiPublicTag_groupsRoute: typeof ApiPublicTag_groupsRoute
  ApiPublicTag_sync_keyRoute: typeof ApiPublicTag_sync_keyRoute
  ApiPublicTagsRoute: typeof ApiPublicTagsRoute
  ApiPublicTags_writeRoute: typeof ApiPublicTags_writeRoute
  ApiPublicKTokenRoute: typeof ApiPublicKTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastebin-key': {
      id: '/pastebin-key'
      path: '/pastebin-key'
      fullPath: '/pastebin-key'
      preLoaderRoute: typeof PastebinKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-key': {
      id: '/get-key'
      path: '/get-key'
      fullPath: '/get-key'
      preLoaderRoute: typeof GetKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tags_write': {
      id: '/api/public/tags_write'
      path: '/api/public/tags_write'
      fullPath: '/api/public/tags_write'
      preLoaderRoute: typeof ApiPublicTags_writeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tags': {
      id: '/api/public/tags'
      path: '/api/public/tags'
      fullPath: '/api/public/tags'
      preLoaderRoute: typeof ApiPublicTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tag_sync_key': {
      id: '/api/public/tag_sync_key'
      path: '/api/public/tag_sync_key'
      fullPath: '/api/public/tag_sync_key'
      preLoaderRoute: typeof ApiPublicTag_sync_keyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tag_groups': {
      id: '/api/public/tag_groups'
      path: '/api/public/tag_groups'
      fullPath: '/api/public/tag_groups'
      preLoaderRoute: typeof ApiPublicTag_groupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/spotify_callback': {
      id: '/api/public/spotify_callback'
      path: '/api/public/spotify_callback'
      fullPath: '/api/public/spotify_callback'
      preLoaderRoute: typeof ApiPublicSpotify_callbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roles': {
      id: '/api/public/roles'
      path: '/api/public/roles'
      fullPath: '/api/public/roles'
      preLoaderRoute: typeof ApiPublicRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reanim.lua': {
      id: '/api/public/reanim.lua'
      path: '/api/public/reanim.lua'
      fullPath: '/api/public/reanim.lua'
      preLoaderRoute: typeof ApiPublicReanimDotluaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pastebin': {
      id: '/api/public/pastebin'
      path: '/api/public/pastebin'
      fullPath: '/api/public/pastebin'
      preLoaderRoute: typeof ApiPublicPastebinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/loader.lua': {
      id: '/api/public/loader.lua'
      path: '/api/public/loader.lua'
      fullPath: '/api/public/loader.lua'
      preLoaderRoute: typeof ApiPublicLoaderDotluaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin.lua': {
      id: '/api/public/admin.lua'
      path: '/api/public/admin.lua'
      fullPath: '/api/public/admin.lua'
      preLoaderRoute: typeof ApiPublicAdminDotluaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/k/$token': {
      id: '/api/public/k/$token'
      path: '/api/public/k/$token'
      fullPath: '/api/public/k/$token'
      preLoaderRoute: typeof ApiPublicKTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetKeyRoute: GetKeyRoute,
  PastebinKeyRoute: PastebinKeyRoute,
  UnlockRoute: UnlockRoute,
  ValidateRoute: ValidateRoute,
  ApiPublicAdminDotluaRoute: ApiPublicAdminDotluaRoute,
  ApiPublicLoaderDotluaRoute: ApiPublicLoaderDotluaRoute,
  ApiPublicPastebinRoute: ApiPublicPastebinRoute,
  ApiPublicReanimDotluaRoute: ApiPublicReanimDotluaRoute,
  ApiPublicRolesRoute: ApiPublicRolesRoute,
  ApiPublicSpotify_callbackRoute: ApiPublicSpotify_callbackRoute,
  ApiPublicTag_groupsRoute: ApiPublicTag_groupsRoute,
  ApiPublicTag_sync_keyRoute: ApiPublicTag_sync_keyRoute,
  ApiPublicTagsRoute: ApiPublicTagsRoute,
  ApiPublicTags_writeRoute: ApiPublicTags_writeRoute,
  ApiPublicKTokenRoute: ApiPublicKTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
